### ISSUE TITLE
windows is not avalaible 

### ISSUE THREAD

**Issue by alphaleadership** [vladmandic/nanodet#1] opened 2021-05-30 08:36 UTC

**Comment by vladmandic** [comment] 2021-05-30 11:43
not sure what you mean, can you elaborate?

**Comment by vladmandic** [comment] 2021-05-30 18:50
closing this as no description of what is the issue is provided.  
when creating an issue, please describe it in more details and also fill the appropriate issue template.

**Closed as completed by vladmandic** 2021-05-30 18:50 UTC
Labels: question

**Comment by alphaleadership** [comment] 2021-05-31 16:21
tfjs is not acces in windows

**Comment by vladmandic** [comment] 2021-05-31 23:31
you still did not post error message or fill the issue template. i have no idea what "tjfs is not acces in windows" means.
